from enum import StrEnum


class Event(StrEnum):
    SYSTEM_BOOT = "SYSTEM_BOOT"
    SYSTEM_READY = "SYSTEM_READY"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    SYSTEM_SHUTDOWN = "SYSTEM_SHUTDOWN"

    CAMERA_STARTING = "CAMERA_STARTING"
    CAMERA_STARTED = "CAMERA_STARTED"
    CAMERA_ERROR = "CAMERA_ERROR"
    CAMERA_STOPPED = "CAMERA_STOPPED"

    FRAME_CAPTURED = "FRAME_CAPTURED"

    FACE_DETECTED = "FACE_DETECTED"
    FACE_LOST = "FACE_LOST"

    USER_PRESENT = "USER_PRESENT"
    USER_AWAY = "USER_AWAY"

    STATE_CHANGED = "STATE_CHANGED"