from enum import StrEnum


class Event(StrEnum):
    SYSTEM_BOOT = "SYSTEM_BOOT"
    SYSTEM_READY = "SYSTEM_READY"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    SYSTEM_SHUTDOWN = "SYSTEM_SHUTDOWN"

    CAMERA_STARTING = "CAMERA_STARTING"
    CAMERA_STARTED = "CAMERA_STARTED"
    CAMERA_ERROR = "CAMERA_ERROR"
    CAMERA_STOPPED = "CAMERA_STOPPED"

    FRAME_CAPTURED = "FRAME_CAPTURED"

    FACE_DETECTED = "FACE_DETECTED"
    FACE_LOST = "FACE_LOST"

    USER_PRESENT = "USER_PRESENT"
    USER_AWAY = "USER_AWAY"

    STATE_CHANGED = "STATE_CHANGED"

    IDENTITY_RECOGNIZED = "IDENTITY_RECOGNIZED"
    IDENTITY_UNKNOWN = "IDENTITY_UNKNOWN"
    IDENTITY_UNCERTAIN = "IDENTITY_UNCERTAIN"

    SECURITY_SUSPICIOUS = "SECURITY_SUSPICIOUS"
    SECURITY_ALERT = "SECURITY_ALERT"

    MULTIPLE_FACES_DETECTED = "MULTIPLE_FACES_DETECTED"
    MULTIPLE_FACES_CONFIRMED = "MULTIPLE_FACES_CONFIRMED"